In [ ]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array((1,2,3,4),dtype=float)
print(b)
print(b.dtype)

[1. 2. 3. 4.]
float64


In [4]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [6]:
c = np.arange(1,-10,-3)
c

array([ 1, -2, -5, -8])

In [7]:
d = np.arange(1,-10,-1, dtype = float)
d

array([ 1.,  0., -1., -2., -3., -4., -5., -6., -7., -8., -9.])

In [8]:
print(d.dtype)

float64


## 等差数列

In [9]:
a = np.linspace(0,10,10)
a

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
b = np.linspace(0,10,10,endpoint=False)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
c = np.linspace(0,10,10,endpoint=False,retstep=True)
c

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), 1.0)

## 等比数列

In [12]:
a = np.logspace(0,9,10)
print(a)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]


In [13]:
b =  np.logspace(0,10,10,endpoint=False)
b

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09])

In [14]:
c = np.logspace(0,9,10,base=2)
c

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

## 二维数组

In [15]:
L = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(L)
print(a)
print(a.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32


In [16]:
 #reshape()函数
d = np.arange(1,10)
print(d)
dd = d.reshape(3,3)
print(dd)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 特殊的二维数组的创立

In [20]:
#元素为1的数组
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#元素为0的数组
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#empty根据指定的形状和数据类型来生成数组
e = np.empty([2,2])
f = np.empty((2,2))
print(e)
print(f)

[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]


In [24]:
#full函数可以根据指定的形状和数据类型生成数组,并用指定的数组进行填充
a =np.full((2,4),10)
print(a)
print(a.dtype)
b =np.full((2,4),10,dtype=float)
print(b)
print(b.dtype)
c =np.full(5,10)
print(c)
print(c.dtype)


[[10 10 10 10]
 [10 10 10 10]]
int32
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]]
float64
[10 10 10 10 10]
int32


In [26]:
#identity函数创建单位矩阵
a = np.identity(3)
print(a)
b = np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
#eye函数创立二维数组,对角线为1
a = np.eye(3,4)
print(a)
b = np.eye(3,4,k=1)#k为对角线偏移量
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 数组的属性

In [31]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)
print(arr.ndim)#维度
print(arr.shape)#形状
print(arr.size)#元素总数
print(arr.dtype)#数据类型
print(arr.itemsize)#每个元素的字节大小
print(arr.nbytes)#总字节数

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32
4
24


In [32]:
#数组的轴
#横轴qxis=1
#竖轴axis=0

In [36]:
#三维数组
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## 数组元素的访问

In [38]:
a= np.array([1,2,3,4,5,6])
print(a[0])
print(a[-1])

1
6


In [40]:
#二维数组的引用
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[0][0])
print(b[1][0])

1
4


## 切片

In [44]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[1:5])
print(a[:4])
print(a[1:])

[2 3 4 5]
[1 2 3 4]
[2 3 4 5 6 7 8 9]


In [50]:
#二维数组切片
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b[1:3,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]
