# Numpy的数据结构

## 数据数组

In [3]:
#一维数组
v = [0.5,0.75,1.0,1.5,2.0]
#生成数组矩阵
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [4]:
#查看矩阵的第一行
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [5]:
#查看数组矩阵第一行的第一个元素
m[1][0]

0.5

In [6]:
#嵌套方法
v1 = [0.5,1.5]
v2 = [1,2]
m = [v1,v2]
c = [m,m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [7]:
 #原数组改变后数组矩阵也会改变
#一维数组
v = [0.5,0.75,1.0,1.5,2.0]
#生成数组矩阵
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [8]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

### 使用copy的deepcopy可以避免

In [9]:
from copy import deepcopy
v = [0.5,0.75,1.0,1.5,2.0]
m = 3 * [deepcopy(v),]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [10]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

## array

In [13]:
v = [0.5,0.75,1.0,1.5,2.0]
import array

In [16]:
#以类型代码f(浮点型)实例化数组对象
a = array.array('f',v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [18]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [19]:
a.extend([5.0,6.75])
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [23]:
import numpy as np

In [24]:
a = np.array([0,0.5,1.0,1.0,1.5,2.0])
a

array([0. , 0.5, 1. , 1. , 1.5, 2. ])

In [25]:
type(a)

numpy.ndarray

In [27]:
a = np.array(['a','b','c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [28]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
a = np.arange(8, dtype=float)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7.]


In [32]:
a[5:]

array([5., 6., 7.])

In [33]:
a[:2]

array([0., 1.])

In [34]:
#元素求总和
a.sum()

28.0

In [35]:
#求元素标准差
a.std()

2.29128784747792

In [36]:
#求元素的累计总和
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

## 数学运算

In [38]:
#list 的乘法是复制元素
l = [0,0.5,1.5,3.0,5.0,0.0,0.5,1.5,3.0,5.0]
2* l

[0,
 0.5,
 1.5,
 3.0,
 5.0,
 0.0,
 0.5,
 1.5,
 3.0,
 5.0,
 0,
 0.5,
 1.5,
 3.0,
 5.0,
 0.0,
 0.5,
 1.5,
 3.0,
 5.0]

In [39]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [41]:
# array的乘法是元素的标量乘法
2 * a 

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [42]:
#计算每个元素的平方
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [44]:
#将a的元素作为指数求幂
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [46]:
# 求每个元素作为底和指数的幂
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [47]:
#计算每个元素的指数值
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [48]:
#计算每个元素的平方根
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [49]:
#计算Python浮点对象的平方根
np.sqrt(2.5)

1.5811388300841898

In [51]:
#使用math进行相同的计算
import math
math.sqrt(2.5)

1.5811388300841898

In [52]:
#math.sqrt()不能直接用在array对象上
math.sqrt(a)

TypeError: only length-1 arrays can be converted to Python scalars

## 多维数组

In [53]:
#用一维的array构造二维对象
b = np.array([a,a * 2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [62]:
#选择第一行
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [55]:
#选择第一行的第三个元素
b[0,2]

2.0

In [63]:
#选择第二列
b[:,1]

array([1., 2.])

In [58]:
#求元素的和
b.sum()

84.0

In [60]:
#沿着列求和
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [64]:
#按行求和
b.sum(axis=1)

array([28., 56.])

### 特殊的数组生成

In [68]:
#创建一个二维整型数组,预先填入0
c = np.zeros((2,3),dtype='i',order='c')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [69]:
#创建一个三维整型数组,预先填入1
c = np.ones([2,3,4],dtype='i',order='c')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [70]:
#创建一个不予先填充任何数值的对象
e = np.empty((2,3,2))
e

array([[[1.02995966e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.23053953e-307, 8.75983079e+164]],

       [[6.55968500e-091, 2.19258064e-056],
        [2.38171534e+179, 1.51898898e-047],
        [3.99910963e+252, 9.73045212e-072]]])

In [71]:
#创建一个对角线矩阵,对角线元素为1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
#创建一维数值之间有均匀间隔的数组
g = np.linspace(5,15,12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

### 元信息

In [76]:
#元素数量
g.size

12

In [77]:
#表示一个元素的字节数
g.itemsize

8

In [80]:
#维数
g.ndim

1

In [81]:
#narray的对象组成
g.shape

(12,)

In [79]:
#元素的dtype
g.dtype

dtype('float64')

In [82]:
#在内存中使用字节的总数
g.nbytes

96

## 改变组成的大小

In [84]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
g.shape

(15,)

In [86]:
np.shape(g)

(15,)

In [88]:
h = g.reshape((5,3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [89]:
#转置
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [90]:
#转置
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [91]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [94]:
#缩小二维数组
np.resize(g,(3,1))

array([[0],
       [1],
       [2]])

In [95]:
#扩大二维数组
np.resize(g,(1,5))

array([[0, 1, 2, 3, 4]])

In [96]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [98]:
#两个array进行水平堆叠
np.hstack((h,2 * h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [100]:
#两个array进行垂直堆叠
np.vstack((h,0.5 * h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [102]:
#数组扁平化处理--降维
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [103]:
#按行进行降维
h.flatten(order = 'c')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [104]:
#按列进行降维
h.flatten(order = 'f')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

## 布尔数组

In [105]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [106]:
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [107]:
h <= 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [108]:
h == 5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [109]:
(h == 5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [112]:
(h > 5) & (h<=12)

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [114]:
#使用布尔值进行索引
h[h > 8]

array([ 9, 10, 11, 12, 13, 14])

In [117]:
h[(h > 5 ) & (h <=12)]

array([ 6,  7,  8,  9, 10, 11, 12])

### np.where()

In [119]:
#h中大于7的元素换为1否则为0
np.where(h>7,1,0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [120]:
#奇数为odd偶数为even
np.where(h% 2 == 0 ,'even','odd')

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [121]:
#大于7元素值翻倍,否则减半
np.where(h >7,h * 2 ,h/2)

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5, 16. ],
       [18. , 20. , 22. ],
       [24. , 26. , 28. ]])

## 代码向量化

In [124]:
np.random.seed(100)
r = np.arange(12).reshape((4,3))
s= np.arange(12).reshape((4,3)) * 0.5

In [125]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [126]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [127]:
r + s


array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [128]:
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [129]:
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [131]:
2*r+3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])