# Pandas的数据结构

DataFrame   带索引的二维数据表
Series      带索引的一维数据表

## DATa Frame

In [32]:
import pandas as pd

In [33]:
df = pd.DataFrame([10,20,30,40],columns=['numbers'],index=['a','b','c','d'])
df

,numbers
a,10
b,20
c,30
d,40


In [34]:
#索引
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [35]:
#列名
df.columns

Index(['numbers'], dtype='object')

In [36]:
#查看元素 
df.loc['c']

numbers    30
Name: c, dtype: int64

In [37]:
#查看多个元素
df.loc[['a','d']]

,numbers
a,10
d,40


In [38]:
#查看多个元素
df.iloc[1:3]

,numbers
b,20
c,30


In [39]:
#求和
df.sum()

numbers    100
dtype: int64

In [40]:
#使用apply方法以向量的方法求平方
df.apply(lambda x: x**2)

,numbers
a,100
b,400
c,900
d,1600


In [41]:
#直接求
df ** 2

,numbers
a,100
b,400
c,900
d,1600


### 增扩df对象内容

In [42]:
# 添加新列,该列包含以元组形式提供的浮点数对象
df['floats'] = (1.5,2.5,3.5,4.5)
df

,numbers,floats
a,10,1.5
b,20,2.5
c,30,3.5
d,40,4.5


In [43]:
# 显示其数据和索引标签
df['floats']

a    1.5
b    2.5
c    3.5
d    4.5
Name: floats, dtype: float64

In [44]:
#增加新的一列
df['names'] = pd.DataFrame(['Yves','Sandra','Lilli','Henry'],['d','a','b','c'])
df

,numbers,floats,names
a,10,1.5,Sandra
b,20,2.5,Lilli
c,30,3.5,Henry
d,40,4.5,Yves


In [45]:
# 添加一行数据
df = pd.concat([df, pd.DataFrame({'numbers': [100], 'floats': [5.75], 'names': ['Jil']},index =['y',])])
df

,numbers,floats,names
a,10,1.50,Sandra
b,20,2.50,Lilli
c,30,3.50,Henry
d,40,4.50,Yves
y,100,5.75,Jil


In [48]:
df = pd.concat([df,pd.DataFrame({'names':['Liz']},index=['z',])])

In [49]:
df

,numbers,floats,names
a,10.0,1.50,Sandra
b,20.0,2.50,Lilli
c,30.0,3.50,Henry
d,40.0,4.50,Yves
y,100.0,5.75,Jil
z,NaN,NaN,Liz


In [51]:
#返回DF的列结构
df.dtypes

numbers    float64
floats     float64
names       object
dtype: object

In [52]:
#求列均值
df[['numbers','floats']].mean()

numbers    40.00
floats      3.55
dtype: float64

In [53]:
#求列标准差
df[['numbers','floats']].std()

numbers    35.355339
floats      1.662077
dtype: float64

In [55]:
#生成随机种子
import numpy as np
np.random.seed(100)

In [57]:
#生成九行四列的标准正太分布
a = np.random.standard_normal((9,4))
a

array([[ 1.18962227, -1.69061683, -1.35639905, -1.23243451],
       [-0.54443916, -0.66817174,  0.00731456, -0.61293874],
       [ 1.29974807, -1.73309562, -0.9833101 ,  0.35750775],
       [-1.6135785 ,  1.47071387, -1.1880176 , -0.54974619],
       [-0.94004616, -0.82793236,  0.10886347,  0.50780959],
       [-0.86222735,  1.24946974, -0.07961125, -0.88973148],
       [-0.88179839,  0.01863895,  0.23784462,  0.01354855],
       [-1.6355294 , -1.04420988,  0.61303888,  0.73620521],
       [ 1.02692144, -1.43219061, -1.8411883 ,  0.36609323]])

In [58]:
df = pd.DataFrame(a)
df

,0,1,2,3
0,1.189622,-1.690617,-1.356399,-1.232435
1,-0.544439,-0.668172,0.007315,-0.612939
2,1.299748,-1.733096,-0.983310,0.357508
3,-1.613579,1.470714,-1.188018,-0.549746
4,-0.940046,-0.827932,0.108863,0.507810
5,-0.862227,1.249470,-0.079611,-0.889731
6,-0.881798,0.018639,0.237845,0.013549
7,-1.635529,-1.044210,0.613039,0.736205
8,1.026921,-1.432191,-1.841188,0.366093


# DataFrame()函数参数

data 数据/字典/ndarray/列表 

index 索引/类似数组 默认为顺序数

columns 索引/类似数组 列标题

dtype  dtype 默认为None 使用/强制的数据类型;否则通过推到得出

copy 布尔值 默认None 从输入复制数据

In [61]:
df.columns=['No1','No2','No3','No4']
df

,No1,No2,No3,No4
0,1.189622,-1.690617,-1.356399,-1.232435
1,-0.544439,-0.668172,0.007315,-0.612939
2,1.299748,-1.733096,-0.983310,0.357508
3,-1.613579,1.470714,-1.188018,-0.549746
4,-0.940046,-0.827932,0.108863,0.507810
5,-0.862227,1.249470,-0.079611,-0.889731
6,-0.881798,0.018639,0.237845,0.013549
7,-1.635529,-1.044210,0.613039,0.736205
8,1.026921,-1.432191,-1.841188,0.366093


In [62]:
df['No2'].mean()

-0.5174882756841399

## 为了高效地处理金融时间序列数据,需要很好的处理时间索引.假设分为四列九行的数据对应于2019年1月开始的月底数据.然后,用date_range()生成一个Datatime对象

In [64]:
#生成时间索引
dates = pd.date_range('2019-1-1',periods=9,freq='M')
dates

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30'],
              dtype='datetime64[ns]', freq='M')

# date_range()函数的参数

start 字符串/日期时间 生成起始日期

end 字符串/日期时间 生成结束日期

period 整数 期数(生成多少个)

freq 字符串/日期偏移 频率字符串(例如5D,2M)2天,五月

In [66]:
df.index =dates
df

,No1,No2,No3,No4
2019-01-31,1.189622,-1.690617,-1.356399,-1.232435
2019-02-28,-0.544439,-0.668172,0.007315,-0.612939
2019-03-31,1.299748,-1.733096,-0.983310,0.357508
2019-04-30,-1.613579,1.470714,-1.188018,-0.549746
2019-05-31,-0.940046,-0.827932,0.108863,0.507810
2019-06-30,-0.862227,1.249470,-0.079611,-0.889731
2019-07-31,-0.881798,0.018639,0.237845,0.013549
2019-08-31,-1.635529,-1.044210,0.613039,0.736205
2019-09-30,1.026921,-1.432191,-1.841188,0.366093


In [67]:
#用ndarray的方法直接访问数据
df.values

array([[ 1.18962227, -1.69061683, -1.35639905, -1.23243451],
       [-0.54443916, -0.66817174,  0.00731456, -0.61293874],
       [ 1.29974807, -1.73309562, -0.9833101 ,  0.35750775],
       [-1.6135785 ,  1.47071387, -1.1880176 , -0.54974619],
       [-0.94004616, -0.82793236,  0.10886347,  0.50780959],
       [-0.86222735,  1.24946974, -0.07961125, -0.88973148],
       [-0.88179839,  0.01863895,  0.23784462,  0.01354855],
       [-1.6355294 , -1.04420988,  0.61303888,  0.73620521],
       [ 1.02692144, -1.43219061, -1.8411883 ,  0.36609323]])

In [69]:
np.array(df)

array([[ 1.18962227, -1.69061683, -1.35639905, -1.23243451],
       [-0.54443916, -0.66817174,  0.00731456, -0.61293874],
       [ 1.29974807, -1.73309562, -0.9833101 ,  0.35750775],
       [-1.6135785 ,  1.47071387, -1.1880176 , -0.54974619],
       [-0.94004616, -0.82793236,  0.10886347,  0.50780959],
       [-0.86222735,  1.24946974, -0.07961125, -0.88973148],
       [-0.88179839,  0.01863895,  0.23784462,  0.01354855],
       [-1.6355294 , -1.04420988,  0.61303888,  0.73620521],
       [ 1.02692144, -1.43219061, -1.8411883 ,  0.36609323]])

## 基本分析

In [71]:
#查看数据的基本信息
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9 entries, 2019-01-31 to 2019-09-30
Freq: M
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   No1     9 non-null      float64
 1   No2     9 non-null      float64
 2   No3     9 non-null      float64
 3   No4     9 non-null      float64
dtypes: float64(4)
memory usage: 360.0 bytes


In [73]:
#查看数据的统计学信息
df.describe()

,No1,No2,No3,No4
count,9.000000,9.000000,9.000000,9.000000
mean,-0.329036,-0.517488,-0.497941,-0.144854
std,1.181335,1.196330,0.853464,0.694755
min,-1.635529,-1.733096,-1.841188,-1.232435
25%,-0.940046,-1.432191,-1.188018,-0.612939
50%,-0.862227,-0.827932,-0.079611,0.013549
75%,1.026921,0.018639,0.108863,0.366093
max,1.299748,1.470714,0.613039,0.736205


In [74]:
#列求和
df.sum(axis=0) #默认为列

No1   -2.961327
No2   -4.657394
No3   -4.481465
No4   -1.303687
dtype: float64

In [75]:
#行求和
df.sum(axis=1)

2019-01-31   -3.089828
2019-02-28   -1.818235
2019-03-31   -1.059150
2019-04-30   -1.880628
2019-05-31   -1.151305
2019-06-30   -0.582100
2019-07-31   -0.611766
2019-08-31   -1.330495
2019-09-30   -1.880364
Freq: M, dtype: float64

In [76]:
#均值,累计求和
df.mean()
df.cumsum()

,No1,No2,No3,No4
2019-01-31,1.189622,-1.690617,-1.356399,-1.232435
2019-02-28,0.645183,-2.358789,-1.349084,-1.845373
2019-03-31,1.944931,-4.091884,-2.332395,-1.487865
2019-04-30,0.331353,-2.621170,-3.520412,-2.037612
2019-05-31,-0.608693,-3.449103,-3.411549,-1.529802
2019-06-30,-1.470921,-2.199633,-3.491160,-2.419534
2019-07-31,-2.352719,-2.180994,-3.253315,-2.405985
2019-08-31,-3.988249,-3.225204,-2.640276,-1.669780
2019-09-30,-2.961327,-4.657394,-4.481465,-1.303687
