# 模型评估与轨道

## 模型评估指标

### 分类学习性能指标

#### 乳腺癌数据集例子

In [3]:

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.metrics import *
bc = load_breast_cancer()
x = bc.data
y = bc.target
print('样本标签分类:',bc['target_names']) #malignant 恶性 benign 良性

样本标签分类: ['malignant' 'benign']


In [5]:
# 使用train_test_split函数将数据集划分为训练集和测试集
# x：特征数据，y：标签数据
# test_size=0.2：测试集占总数据的20%，训练集占80%
# random_state=0：设置随机种子，确保每次运行划分结果一致
# stratify=y：按照标签y的分布进行分层抽样，保持训练集和测试集中各标签比例与原数据集一致
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0, stratify=y)

# 对数据进行标准化处理
# 创建StandardScaler标准化器，并使用训练集数据拟合标准化器（计算均值和标准差）
scaler = StandardScaler().fit(x_train)

# 使用拟合好的标准化器对训练集特征进行标准化转换
x_train_scaler = scaler.transform(x_train)

# 使用同样的标准化器（基于训练集计算的均值和标准差）对测试集特征进行标准化转换
# 注意：测试集必须使用训练集的标准化参数，避免数据泄露
x_test_scaler = scaler.transform(x_test)

# 创建线性支持向量分类器(LinearSVC)模型，设置随机种子保证结果可复现
cls = LinearSVC(random_state=0)

# 使用标准化后的训练集特征和对应的标签训练模型
cls.fit(x_train_scaler, y_train)

# 使用训练好的模型对标准化后的测试集特征进行预测，得到预测标签
y_test_pred = cls.predict(x_test_scaler)

# 计算测试集上的准确率：正确预测的样本数占总测试样本数的比例
acc_test = accuracy_score(y_test, y_test_pred)

# 打印测试集的准确率结果
print('测试集的准确率:', acc_test)

测试集的准确率: 0.9736842105263158


In [6]:
#通过参数pos_label=0指定标签0为正类
recall_test = recall_score(y_test,y_test_pred,pos_label=0)
print('测试集召回率(真正率):',recall_test)

测试集召回率(真正率): 0.9523809523809523


In [7]:
#通过参数pos_label=0指定标签0为正类
precision_test = precision_score(y_test,y_test_pred,pos_label=0)
print('测试集精度:',precision_test)

测试集精度: 0.975609756097561


In [8]:
f1_test = f1_score(y_test,y_test_pred,pos_label=0)
print('测试集f1-score:',f1_test)

测试集f1-score: 0.963855421686747


In [12]:
#通过labels指定的混淆矩阵中各类别标签的排列顺序
print('混淆矩阵:\n',confusion_matrix(y_test,y_test_pred,labels=[1,0]),sep=' ')

混淆矩阵:
 [[71  1]
 [ 2 40]]


In [17]:
#0 恶性 1 良性
tn,fp,fn,tp = confusion_matrix(y_test,y_test_pred,labels=[1,0]).ravel()
print('手工计算的测试集准确率:',(tn+tp)/(tn+tp+fn+fp))
print('手工计算的测试集召回率:',tp/(tp+fn))
print('手工计算的测试集精度:',tp/(tp+fp))
print('手工计算的测试集假正率:',fp/(fp+tn))
print('手工计算的测试集f1-score:',tp/(tp+(fn+fp)/2))
print('分类报告:\n',classification_report(y_test,y_test_pred))

手工计算的测试集准确率: 0.9736842105263158
手工计算的测试集召回率: 0.9523809523809523
手工计算的测试集精度: 0.975609756097561
手工计算的测试集假正率: 0.013888888888888888
手工计算的测试集f1-score: 0.963855421686747
分类报告:
               precision    recall  f1-score   support

           0       0.98      0.95      0.96        42
           1       0.97      0.99      0.98        72

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



#### iris数据集

In [31]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.metrics import *
iris = load_iris()
x = iris.data
y = iris.target
print('鸢尾花的种类:',iris['target_names'])

鸢尾花的种类: ['setosa' 'versicolor' 'virginica']


In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0,stratify=y)
#对训练集特化
scaler = StandardScaler().fit(x_train)
x_train_scaler = scaler.transform(x_train)
x_test_scaler = scaler.transform(x_test)
cls = LinearSVC(random_state=0)
cls.fit(x_train_scaler,y_train)
y_test_pred = cls.predict(x_test_scaler)
acc_test = accuracy_score(y_test,y_test_pred)
print('测试集所有类别准确率:',acc_test)

测试集所有类别准确率: 0.9777777777777777


In [34]:
labels = (0,1,2)
cm = confusion_matrix(y_test,y_test_pred,labels=labels)
print('混淆矩阵:\n',cm,sep=' ')
print('分类报告:\n',classification_report(y_test,y_test_pred))

混淆矩阵:
 [[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]
分类报告:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.94      1.00      0.97        15
           2       1.00      0.93      0.97        15

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [35]:
# 遍历每个类别，将其作为正类进行评估
for pos_label in labels:
    print(f"{pos_label}为正类时:")  # 使用f-string更简洁地格式化输出
    
    # 计算测试集的召回率（真正率）
    # 注意：多分类中当指定labels=[pos_label]时，weighted平均可能不是最佳选择
    recall_test = recall_score(y_test, y_test_pred, labels=[pos_label], average='weighted')
    print(f"\t测试集召回率(真正率): {recall_test}")
    
    # 计算测试集的精确率
    preision_test = precision_score(y_test, y_test_pred, labels=[pos_label], average='weighted')
    print(f"\t测试集精确率: {preision_test}")
    
    # 计算F1分数
    f1 = f1_score(y_test, y_test_pred, labels=[pos_label], average='weighted')
    print(f"\tf1-score: {f1}")
    
    # 真正例：预测为正类且实际为正类的样本数
    tp = cm[pos_label, pos_label]
    
    # 假负例：实际为正类但预测为其他类的样本数总和
    fn = 0
    for j in labels:
        if j != pos_label:
            fn += cm[pos_label, j]
    
    # 假正例：实际为其他类但预测为正类的样本数总和
    fp = 0
    for i in labels:
        if i != pos_label:
            fp += cm[i, pos_label]
    
    # 真负例：实际为其他类且预测为其他类的样本数总和
    tn = 0
    for i in labels:
        for j in labels:
            # 修正：将位运算&改为逻辑运算and
            if i != pos_label and j != pos_label:
                tn += cm[i, j]
    
    # 计算准确率（所有样本中预测正确的比例）
    # 修正：这里是总体准确率，不只是"分正负类"的准确率
    accuracy = (tn + tp) / (tn + tp + fn + fp)
    print(f"\t手工计算的测试集准确率: {accuracy}")
    
    # 召回率（真正率）：正类中被正确预测的比例
    recall = tp / (tp + fn) if (tp + fn) != 0 else 0  # 避免除零错误
    print(f"\t手工计算的测试集召回率(真正率): {recall}")
    
    # 精确率：预测为正类的样本中实际为正类的比例
    precision = tp / (tp + fp) if (tp + fp) != 0 else 0  # 避免除零错误
    print(f"\t手工计算的测试集精确率: {precision}")
    
    # 假正率：负类中被错误预测为正类的比例
    fpr = fp / (fp + tn) if (fp + tn) != 0 else 0  # 避免除零错误
    print(f"\t手工计算的测试集假正率: {fpr}")

0为正类时:
	测试集召回率(真正率): 1.0
	测试集精确率: 1.0
	f1-score: 1.0
	手工计算的测试集准确率: 1.0
	手工计算的测试集召回率(真正率): 1.0
	手工计算的测试集精确率: 1.0
	手工计算的测试集假正率: 0.0
1为正类时:
	测试集召回率(真正率): 1.0
	测试集精确率: 0.9375
	f1-score: 0.9677419354838709
	手工计算的测试集准确率: 0.9777777777777777
	手工计算的测试集召回率(真正率): 1.0
	手工计算的测试集精确率: 0.9375
	手工计算的测试集假正率: 0.03333333333333333
2为正类时:
	测试集召回率(真正率): 0.9333333333333333
	测试集精确率: 1.0
	f1-score: 0.9655172413793104
	手工计算的测试集准确率: 0.9777777777777777
	手工计算的测试集召回率(真正率): 0.9333333333333333
	手工计算的测试集精确率: 1.0
	手工计算的测试集假正率: 0.0


### 回归学习性指标

In [40]:
# 1. 导入所需库
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

# 2. 构造示例数据（模拟“广告投入-销售额”回归任务）
# 自变量X：2个特征（电视广告投入、线上广告投入，单位：万元）
# 因变量y_true：销售额（单位：万元，真实关系：销售额=5 + 2*电视广告 + 3*线上广告 + 少量噪声）
np.random.seed(42)  # 固定随机种子，确保结果可复现
X = np.random.randint(10, 100, size=(50, 2))  # 50个样本，2个自变量
noise = np.random.normal(0, 5, size=50)  # 随机噪声
y_true = 5 + 2*X[:, 0] + 3*X[:, 1] + noise  # 真实销售额

# 3. 训练线性回归模型并生成预测值
model = LinearRegression()
model.fit(X, y_true)  # 拟合模型
y_pred = model.predict(X)  # 生成预测值

# 4. 计算R²（使用sklearn内置函数）
r2 = r2_score(y_true, y_pred)
print(f"模型R²值：{r2:.4f}")  # 输出：模型R²值：0.9866（拟合效果优秀）

# 5. 计算调整后R²（手动实现公式）
n = X.shape[0]  # 样本数量
k = X.shape[1]  # 自变量个数
adjusted_r2 = 1 - ((1 - r2) * (n - 1)) / (n - k - 1)
print(f"模型调整后R²值：{adjusted_r2:.4f}")  # 输出：模型调整后R²值：0.9861


模型R²值：0.9982
模型调整后R²值：0.9981


### 聚类学习性指标

In [41]:
import numpy as np
from sklearn.metrics import silhouette_score

# 1. 准备数据：6个样本的坐标（二维特征）
X = np.array([
    [1, 2],   # A
    [2, 3],   # B
    [3, 2],   # C
    [6, 7],   # D
    [7, 8],   # E
    [8, 7]    # F
])

# 2. 正确的聚类标签（簇1：0，簇2：1）
labels = np.array([0, 0, 0, 1, 1, 1])

# 3. 计算整体轮廓系数（默认用欧氏距离）
sil_score = silhouette_score(X, labels)
print(f"正确聚类的整体轮廓系数：{sil_score:.4f}")  # 输出：0.7868（与手动计算一致）

# 4. 错误的聚类标签（模拟糟糕的聚类结果）
bad_labels = np.array([0, 0, 1, 0, 1, 1])
bad_sil_score = silhouette_score(X, bad_labels)
print(f"错误聚类的整体轮廓系数：{bad_sil_score:.4f}")  # 输出：0.2937（显著降低）

正确聚类的整体轮廓系数：0.7724
错误聚类的整体轮廓系数：0.0161


### 聚类学习性指标

In [38]:
#轮廓系数Silhoutette Coefficient
import numpy as np
from sklearn.metrics import silhouette_score

# 1. 准备数据：6个样本的坐标（二维特征）
X = np.array([
    [1, 2],   # A
    [2, 3],   # B
    [3, 2],   # C
    [6, 7],   # D
    [7, 8],   # E
    [8, 7]    # F
])

# 2. 正确的聚类标签（簇1：0，簇2：1）
labels = np.array([0, 0, 0, 1, 1, 1])

# 3. 计算整体轮廓系数（默认用欧氏距离）
sil_score = silhouette_score(X, labels)
print(f"正确聚类的整体轮廓系数：{sil_score:.4f}")  # 输出：0.7868（与手动计算一致）

# 4. 错误的聚类标签（模拟糟糕的聚类结果）
bad_labels = np.array([0, 0, 1, 0, 1, 1])
bad_sil_score = silhouette_score(X, bad_labels)
print(f"错误聚类的整体轮廓系数：{bad_sil_score:.4f}")  # 输出：0.2937（显著降低）

正确聚类的整体轮廓系数：0.7724
错误聚类的整体轮廓系数：0.0161


## 交叉验证

### 回归模型中的k折交叉验证

In [5]:
#以联合循环发电厂为例,进行三折叠交叉验证 三折叠怎么折都有面
import pandas as pd
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
#读取数据
ccpp_data = pd.read_csv('./data/CCPP_data.csv',index_col=None)
x = ccpp_data.iloc[:,:4].values.astype(float)
y = ccpp_data.iloc[:,-1:].values.astype(float)
m = LinearRegression()
#3折叠交叉验证,默认采取标准交叉验证
scores = cross_val_score(m,x,y,cv=3)
print(f'各次迭代的决定系数:{scores}')
print(f'平均决定系数:{scores.mean()}')

各次迭代的决定系数:[0.92929563 0.9312216  0.92522815]
平均决定系数:0.9285817923317791


In [7]:
#也可以通过交叉分离器来打乱数据,达到类似的分层交叉的效果
kfold = KFold(n_splits=3,shuffle=True,random_state=10)
print('-'*5 + '打乱数据后' + '-'*5)
#进行三折交叉验证
scores = cross_val_score(m,x,y,cv=kfold)
print(f'各次迭代的决定系数:{scores}')
print(f'平均决定系数:{scores.mean()}')
y_pred = cross_val_predict(m,x,y,cv=kfold)
print('前两个样本的预测目标值:\n',y_pred[:2],sep='')

-----打乱数据后-----
各次迭代的决定系数:[0.93313583 0.92437607 0.92792968]
平均决定系数:0.9284805286134005
前两个样本的预测目标值:
[[467.24829864]
 [444.11689024]]


### 分类模型中的k折交叉验证

In [9]:
from sklearn.datasets import load_iris
from sklearn.svm import LinearSVC
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import KFold
iris_data = load_iris()
x,y = iris_data.data,iris_data.target
#构建模型
m = LinearSVC(random_state=1,max_iter=10000)
#cross_val_score用于分类,默认采用分层交叉验证
scores = cross_val_score(m,x,y,cv=3)
print(f'测试准确率:{scores}')
print(f'平均准确率:{scores.mean()}')

测试准确率:[1.   0.94 0.96]
平均准确率:0.9666666666666667


In [10]:
#也可以通过交叉分离器来打乱数据,强制使用标准k折交叉验证
kfold = KFold(n_splits=3,shuffle=False)
print('-'*5 + '打乱数据后' + '-'*5)
#进行三折交叉验证
scores = cross_val_score(m,x,y,cv=kfold)
print(f'测试准确率:{scores}')
print(f'平均测试准确率:{scores.mean()}')
y_pred = cross_val_predict(m,x,y,cv=kfold)
print('前两个样本的预测标签值:\n',y_pred[:2],sep='')

-----打乱数据后-----
测试准确率:[0. 0. 0.]
平均测试准确率:0.0
前两个样本的预测标签值:
[1 1]


## 轨道的创建和使用

### 创建和使用轨道

In [11]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline
iris_data = load_iris()
x,y = iris_data.data,iris_data.target
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

#### 创建轨道的方法:1

In [12]:
pipe = Pipeline([('scaler',StandardScaler()),('svc',SVC(kernel='linear',random_state=0))])
#训练轨道
pipe.fit(x_train,y_train)
print('模型在训练集上预测的准确率:',pipe.score(x_train,y_train))
print('模型在测试集上预测的准确率:',pipe.score(x_test,y_test))
print('预测测试集第一个样本的类别编码:',pipe.predict(x_test[:1]))

模型在训练集上预测的准确率: 0.9583333333333334
模型在测试集上预测的准确率: 1.0
预测测试集第一个样本的类别编码: [2]


In [13]:
#查看所有步骤
print('所有步骤名称,参数等信息:\n',pipe.steps,sep = '')
#查看指定步骤
print('步骤svc的信息:',pipe.named_steps['svc'],sep='')
print('模型参数:',pipe.get_params(),sep='')

所有步骤名称,参数等信息:
[('scaler', StandardScaler()), ('svc', SVC(kernel='linear', random_state=0))]
步骤svc的信息:SVC(kernel='linear', random_state=0)
模型参数:{'memory': None, 'steps': [('scaler', StandardScaler()), ('svc', SVC(kernel='linear', random_state=0))], 'transform_input': None, 'verbose': False, 'scaler': StandardScaler(), 'svc': SVC(kernel='linear', random_state=0), 'scaler__copy': True, 'scaler__with_mean': True, 'scaler__with_std': True, 'svc__C': 1.0, 'svc__break_ties': False, 'svc__cache_size': 200, 'svc__class_weight': None, 'svc__coef0': 0.0, 'svc__decision_function_shape': 'ovr', 'svc__degree': 3, 'svc__gamma': 'scale', 'svc__kernel': 'linear', 'svc__max_iter': -1, 'svc__probability': False, 'svc__random_state': 0, 'svc__shrinking': True, 'svc__tol': 0.001, 'svc__verbose': False}


#### 创建管道的方法:2

In [14]:
pipe = make_pipeline(StandardScaler(),SVC(kernel='linear',random_state=0))

#### 交叉验证中使用管道

In [15]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline

In [16]:
iris_data = load_iris()
x,y = iris_data.data,iris_data.target
#创建轨道
pipe = make_pipeline(StandardScaler(),SVC(kernel='linear',random_state=0))
scores = cross_val_score(pipe,x,y) #交叉验证时使用管道
print('交叉验证各轮准确率:\n',scores,sep='')
print('平均准确率:\n',scores.mean())


交叉验证各轮准确率:
[0.96666667 1.         0.93333333 0.93333333 1.        ]
平均准确率:
 0.9666666666666668
