In [1]:
import numpy as np

In [6]:
a = np.ones((3,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
b = np.zeros((3,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
c = np.linspace(0,100,20)
c

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [9]:
d = np.arange(10,50,2)
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [11]:
e = np.random.randint(1,4,(2,3))
e

array([[3, 2, 1],
       [2, 3, 1]])

In [12]:
arr = np.random.randint(1,100,(5,6))
arr

array([[93, 74, 42, 63, 77, 62],
       [37, 31, 80, 58, 74, 81],
       [25, 89, 61, 50, 68, 68],
       [78, 41, 99, 78, 64, 13],
       [69, 20, 56, 91, 73, 39]])

In [13]:
arr[1]#取一行

array([37, 31, 80, 58, 74, 81])

In [16]:
arr[[1,3,4]]#取多行

array([[37, 31, 80, 58, 74, 81],
       [78, 41, 99, 78, 64, 13],
       [69, 20, 56, 91, 73, 39]])

In [18]:
#切片
#行
arr[0:2]

array([[93, 74, 42, 63, 77, 62],
       [37, 31, 80, 58, 74, 81]])

In [19]:
#列
arr[:,0:2]

array([[93, 74],
       [37, 31],
       [25, 89],
       [78, 41],
       [69, 20]])

In [20]:
arr[0:2,0:2]

array([[93, 74],
       [37, 31]])

In [21]:
#反转
#行倒置
arr[::-1]

array([[69, 20, 56, 91, 73, 39],
       [78, 41, 99, 78, 64, 13],
       [25, 89, 61, 50, 68, 68],
       [37, 31, 80, 58, 74, 81],
       [93, 74, 42, 63, 77, 62]])

In [22]:
#列倒置
arr[:,::-1]

array([[62, 77, 63, 42, 74, 93],
       [81, 74, 58, 80, 31, 37],
       [68, 68, 50, 61, 89, 25],
       [13, 64, 78, 99, 41, 78],
       [39, 73, 91, 56, 20, 69]])

In [23]:
#行列都倒置
arr[::-1,::-1]

array([[39, 73, 91, 56, 20, 69],
       [13, 64, 78, 99, 41, 78],
       [68, 68, 50, 61, 89, 25],
       [81, 74, 58, 80, 31, 37],
       [62, 77, 63, 42, 74, 93]])

In [24]:
#数组拼接
a = np.random.randint(0,100,(3,4))
b = np.random.randint(0,50,(3,4))

In [26]:
#列拼接
c = np.concatenate((a,b),axis=0)
c

array([[87,  2, 48, 42],
       [70, 99,  6, 41],
       [29, 97,  5, 33],
       [36, 43, 34, 13],
       [25, 12, 43, 48],
       [21,  1, 46, 47]])

In [27]:
#行拼接
c = np.concatenate((a,b),axis=1)
c

array([[87,  2, 48, 42, 36, 43, 34, 13],
       [70, 99,  6, 41, 25, 12, 43, 48],
       [29, 97,  5, 33, 21,  1, 46, 47]])

In [28]:
#单位矩阵
e = np.eye(6)

In [29]:
e


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [1]:
import pandas

In [2]:
dit = {
    '张三':[150,150,150],
    '李四':[0,0,0]
}
index = [
    '语文','数学','英语'
]

In [3]:
df = pandas.DataFrame(dit,index)

In [4]:
df


,张三,李四
语文,150,0
数学,150,0
英语,150,0
